###服务注册到eureka地址
eureka:
  client:
    service-url:
           defaultZone: http://localhost:8100/eureka
spring:
  application:
    ####注册中心应用名称
    name: config-server
  cloud:
    config:
      server:
        git:
          ###git环境地址
          uri: https://github.com/XiaoFengSophia/spring-cloud-config.git
          #uri: git@github.com:XiaoFengSophia/spring-cloud-config.git
          ####搜索目录
          search-paths:
            - config-repo 
      ####读取分支      
      label: master
#  boot: 
#    admin:
#      client:
#        url: http://localhost:8000 
####端口号      
server:
  port: 8888
